from sqlalchemy import Column, String, Integer, Float, BigInteger, Text
from app.db.base import Base

class R20Student(Base):
    __tablename__ = "r20e3s1"

    ID = Column(String(50), primary_key=True, index=True)
    NAME = Column(String(50))
    GENDER = Column(String(50))
    CET_HT_NO = Column(BigInteger)
    pucbranch = Column(String(50))
    class_p1 = Column("Class(p1)", String(50))
    caste = Column("CASTE", String(50))
    class_p2 = Column("Class(p2)", String(50))
    DOB = Column(String(50))
    branch = Column(String(50))
    FATHER = Column(String(50))
    MANDAL = Column(String(50))
    DISTRICT = Column(String(50))
    SCHOOL = Column(String(50))
    PHONE2 = Column(Text)
    SSC = Column(BigInteger)
    SSC_BOARD = Column(Text)
    PHONE = Column(Text)
    MOTHER = Column(Text)
    BLOOD_GROUP = Column("BLOOD GROUP", Text)
    Parent = Column(Text)
    ADDRESS = Column(Text)
    e1sem1 = Column(Float)
    e1sem2 = Column(Float)
    e2sem1 = Column(Float)
    e2sem2 = Column(Float)
    BRANCH_1 = Column(String(50))
    CGPA = Column(Float)
    AGE = Column(Integer)
    Latitude = Column(Float)
    Longitude = Column(Float)
    IMG = Column(String(128))
    p1sem1 = Column(Float)
    p1sem2 = Column(Float)
    p2sem1 = Column(Float)
    p2sem2 = Column(Float)
    e3sem1 = Column(Float)
    RANK = Column(BigInteger)

class R21Student(Base):
    __tablename__ = "r21students"

    ID = Column(String(50), primary_key=True, index=True)
    NAME = Column(String(50))
    HALL_TICKET = Column(Float)
    SSC_CGPA = Column(Float)
    DOB = Column(String(50))
    PHONE = Column(String(50))
    GENDER = Column(String(50))
    BRANCH = Column(String(50))
    CURRENT_YEAR = Column(String(50))
    HOSTEL_ROOM = Column(String(50))
    FATHER = Column(String(50))
    MOTHER = Column(String(50))
    BLOOD_GROUP = Column(String(50))
    PHONE2 = Column(String(50))
    ADDRESS = Column(Text)
    IMAGE = Column(String(128))
    E1SEM1 = Column(Float)
    E1SEM2 = Column(Float)